name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Install Bison'
      run: sudo apt install bison
    - name: 'Create env file'
      run: |
        touch .env
        echo CC="gcc" >> .env
        echo BC="bison" >> .env
        cat .env
    - name: make
      run: make
    - name: test
      run: ./main programs/1.2.6.a
