name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Install bison'
      run: sudo apt install bison
    - name: 'Install sshpass'
      run: sudo apt-get install sshpass
    - name: 'Install scp'
      run: sudo apt-get install openssh-client
    - name: 'Create env file'
      run: |
        touch .env
        echo CC="gcc" >> .env
        echo BC="bison" >> .env
        cat .env
    - name: make
      run: make all 
    - name: upload 
      run: |
        sshpass -p $(JOSEPH_PASSWORD) scp markov-wasm $(JOSEPH_USER)@$(JOSEPH_IP):/var/www/joseph.computer/github-artifact
    # - name: test
    #   run: ./main programs/1.2.6.a
