name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 'Install bison'
      run: sudo apt install bison
    - name: 'Install sshpass'
      run: sudo apt-get install sshpass
    - name: 'Install scp'
      run: sudo apt-get install openssh-client
    - name: 'Create env file'
      run: |
        touch .env
        echo CC="gcc" >> .env
        echo BC="bison" >> .env
        cat .env
    - name: make
      run: make all 
    - name: upload 
      env: 
        remote_password: ${{ secrets.JOSEPH_PASSWORD }}
        remote_user: ${{ secrets.JOSEPH_USER }}
        remote_ip: ${{ secrets.JOSEPH_IP }}
        remote_destination: ${{ secrets.JOSEPH_DESTINATION }}      
      run: |
        ls -al
        sshpass -p "$remote_password" scp -o StrictHostKeyChecking=no markov-wasm $remote_user@$remote_ip:$remote_destination/
    # - name: test
    #   run: ./main programs/1.2.6.a
